services:
  db:
    image: postgres:18
    env_file:
      - .env
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  db_data: