services:
  db:
    image: postgres:18
    env_file:
      - .env
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9003:9000"
      - "9004:9001"
    volumes:
      - ./dev-data/rustfs:/data
    environment:
      - RUSTFS_ACCESS_KEY=${S3_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=${S3_SECRET_KEY}

volumes:
  db_data:
