import * as fs from "node:fs";

const sourceEnvFile = ".env";
const targetEnvFile = "packages/postpin/.env";

if (!fs.existsSync(sourceEnvFile)) {
	console.error(`Source env file "${sourceEnvFile}" does not exist.`);
	process.exit(1);
}

let envContent = fs.readFileSync(sourceEnvFile, "utf-8");
envContent = `# DO NOT EDIT!\n# This file is automatically generated by the sync-env.mjs script.\n# Instead, edit the source env file "${sourceEnvFile}".\n\n${envContent}`;
fs.writeFileSync(targetEnvFile, envContent);
